### ISSUE TITLE
Not upgraded to config version 2

### ISSUE THREAD

**Issue by melissa-mg** [dbt-labs/adwords#23]
This package is no longer compatible with dbt v0.19.0. Is this still being actively maintained?

```
Encountered an error:
Runtime Error
  Failed to read package: Runtime Error
    Invalid config version: 1, expected 2
```

**Comment by scanasca** [comment]
Any help here?

**Comment by jtcohen6** [comment]
I believe this was resolved by https://github.com/fishtown-analytics/adwords/pull/22
